laravel installation dynamic

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -29,7 +29,9 @@ COPY . .
 COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf
 COPY ./docker/supervisord.conf /etc/supervisord.conf
 
-RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache && \
+
+RUN [ -d /var/www/html/storage ] && chown -R www-data:www-data /var/www/html/storage || echo "storage not found" && \
+    [ -d /var/www/html/bootstrap/cache ] && chown -R www-data:www-data /var/www/html/bootstrap/cache || echo "cache not found" && \
     git config --global --add safe.directory /var/www/html
 # for windows
 # 0.484 fatal: detected dubious ownership in repository at '/var/www/html'
@@ -37,9 +39,17 @@ RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cac
 # 0.484
 # 0.484   git config --global --add safe.directory /var/www/html
 
-RUN composer install --no-interaction --prefer-dist --optimize-autoloader \
-    && composer dump-autoload -o \
-    && php artisan package:discover
+# RUN composer install --no-interaction --prefer-dist --optimize-autoloader \
+#     && composer dump-autoload -o \
+#     && php artisan package:discover
+RUN if [ -f artisan ] && [ -f composer.json ]; then \
+    composer install --no-interaction --prefer-dist --optimize-autoloader && \
+    composer dump-autoload -o && \
+    php artisan package:discover; \
+    else \
+    echo "Laravel not found. Skipping composer install and artisan commands."; \
+    fi
+
 
 RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache
 RUN chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache
